# Generated by Django 5.0.1 on 2025-01-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_flat_number_lead_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ca_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='cce_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
