# Generated by Django 5.0.1 on 2025-02-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
